version: '3.5'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: identity-server
    restart: unless-stopped
    ports:
      - "8443:8443"
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: jdbc:postgresql://${KC_DB_HOST}:${KC_DB_PORT}/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HTTP_ENABLED: "false"
    volumes:
      - ./certs:/etc/x509/https:ro
      - keycloak_data:/opt/keycloak/data
    command:
      - start
      - --https-certificate-file=/etc/x509/https/tls.crt
      - --https-certificate-key-file=/etc/x509/https/tls.key

volumes:
  keycloak_data:
