version: '3.5'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start-dev

volumes:
  keycloak_data: